### ISSUE TITLE
 STC8H8K64U dev board

### ISSUE THREAD

**Issue by ITstreet1** [ma6254/Arduino_Core_STC#2]
Hi, 
I have this development board
https://www.aliexpress.com/item/1005005551915125.html
Any help on how to upload a basic Blink sketch on it? Do I need a programmer? Do I have to put it in boot mode somehow? 

Thank you in advance.

**Comment by ma6254** [comment]
You can compile the code to get the `hex` file, and then use STC’s official `STC-ISP.exe` tool to burn it in

**Comment by ma6254** [comment]
http://www.stcmcudata.com/STCISP/stc-isp-15xx-v6.92I.zip
